### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by nicholasbulka** [bminer/ws-wrapper#11]
Can you make type definitions for this for Typescript?

**Comment by nicholasbulka** [comment]
I took a quick glance but wasn’t sure about a few of the conditionally invoked class variables

**Comment by bminer** [comment]
Honestly, I'm a TypeScript n00b.  I would have no idea what I'm doing.  Perhaps you could post a link here or submit a PR for me to review?

**Comment by bminer** [comment]
Closing this issue for now due to age. Please feel free to comment here or re-open.
