### ISSUE TITLE
Export ES Modules

### ISSUE THREAD

**Issue by srcrip** [bminer/ws-wrapper#15]
Could we get some ES module export up in here for this and the server package?

**Comment by bminer** [comment]
Could you clarify this issue? Are you suggesting a re-write using ES modules instead of CommonJS?

**Comment by bminer** [comment]
Closing this issue due to staleness. Also, as far as I know, Node.js still prefers the CommonJS module style, and most bundlers can handle either CommonJS or ESM. I'd be happy to continue this conversation if this is still relevant.
