### ISSUE TITLE
Compile to ES5

### ISSUE THREAD

**Issue by kerrickwoyshner** [bminer/ws-wrapper#5]
React's automatic build script does not work because this project does not provide ES5 code.

See https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Also, providing ES5 support will make this work on IE 10/11.

**Comment by bminer** [comment]
It should be noted that this has been fixed in react-scripts@2

https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify
