### ISSUE TITLE
whos better this or socket io?

### ISSUE THREAD

**Issue by Succubussix** [bminer/ws-wrapper#7]

**Comment by bminer** [comment]
A good question.  I prefer this library, of course, but I'll try to be fair and unbiased...  :)

Reasons to use ws-wrapper:
- Lightweight
- 1 light dependency
- Core functionality is there
- Easily extensible
- Less configuration to ponder about

Reasons to use socket.io:
- More functionality out-of-the-box
- Larger community
- Better documentation

If I missed anything, please feel free to post back here.  I'm closing this issue for now.

**Comment by FifineHex** [comment]
just incrementing, socket.io is a bottleneck

![53293184-5acf6080-378c-11e9-8753-c2a3f11a8b07](https://user-images.githubusercontent.com/14141025/67370123-88a1ba80-f550-11e9-89a3-3be469623f64.png)

**Comment by Succubussix** [comment]
that last one is nice I wonder if they can do that on node too xD.

**Comment by Succubussix** [comment]
add this on chart

@GustavoMorais

socketcluster vs ClusterWS vs  uWebSockets-bindings

**Comment by FifineHex** [comment]
"uWebSockets-bindings" is already on the chart, it's the last "uWS C++", but this particular version you mentioned is old and has no recommended use, since the author has changed the way it works

"ClusterWS" is based on "uWS" at least version 3.3.0, but you can't use a newer node version (this is mentioned on the git page itself), so if you want to use a newer version you will need to wait for version 4.0

SocketCluster => https://socketcluster.io/#!/performance

**Comment by Succubussix** [comment]
hmmm, that SocketCluster is interesting. but the docs are incomplete

**Comment by FifineHex** [comment]
I found another version of **ClusterWS** which is based on **uWS v0.14** but you will be able to run on a newer node version.
https://github.com/ClusterWS/cWS

the choice depends on your needs, if your application is going to have more than 42k simultaneous connections then choose **ClusterWS/cWS**, if you don't need all that firepower you can use this current repo (I use it too and never let me down, he uses WS as his engine), **SocketCluster** is also a viable option for scalability, it has built-in load balancer options

**Comment by Succubussix** [comment]
sometimes not all wrapper perform same on their naked version xD but I will give that a try

**Comment by Succubussix** [comment]
I end up using socketcluster XD I created angular module for it... it works just like socket io.. 90% xD ClusterWS/cWS seems too slow to connect.. I need to emit a message OnInit ... not afterviewinit.. even at afterviewinit the clusterws seems not connected yet.. it will throw ```Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.``` but socketcluster works nice it works the way I wanted. you can even emit right after you call the connect unlike clusterws ... both socketcluster  and clusterws  had power to utilizes all the cores its just ClusterWS/cWS still not ready for production .. it will be deprecated soon because v4 will come XD
