### ISSUE TITLE
"a" leading sendEvent data

### ISSUE THREAD

**Issue by cTatu** [bminer/ws-wrapper#8]
Hi, the wrapper is amazing but I have a question about the `_sendEvent` function (line `249`). I'm trying to implement the same wrapper for [this flutter websocket plugin](https://github.com/dart-lang/web_socket_channel) and looking at the raw data sent by your wrapper I noticed the key `"a"` on the object that will be sent to the other end of the socket. Why is that? I tried removing it and stringify the `args` object directly also works. Moreover removing it will make it easier for my to parse it on flutter.

Thank you!

https://github.com/bminer/ws-wrapper/blob/0e544c614efbaf71128c82b9e945ecba272936b3/lib/wrapper.js#L247-L252

**Comment by bminer** [comment]
It's just part of the [protocol](https://github.com/bminer/ws-wrapper#protocol). Honestly, I chose `a` because it's short and requires little bandwidth.  "a" stands for "arguments".

Please let me know if you have any other questions.  Best of luck!

**Comment by cTatu** [comment]
Awesome thank you, I was able to implement it successfully tough [here it is](https://github.com/cTatu/ws-wrapper-dart2) :)

One more question, this wrapper supports binary data? I think would require adding a raw method of sending the data, without encoding it to json.

**Comment by bminer** [comment]
Yes, the wrapper does support binary data, and it simply ignores any message that is invalid JSON.

From the docs:

> If the message received by the WebSocket is not valid JSON or if the parsed Object does not match one of the above message types, then the message is simply ignored by ws-wrapper. Also if the JSON message contains a `ws-wrapper` property with the value `false`, the message will be ignored. This allows other libraries to use the same WebSocket and send messages that will not be processed by ws-wrapper.

Hope that helps!
